/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    NeonGate: typeof import('./resources/js/Components/NeonGate.vue')['default']
    NeonNav: typeof import('./resources/js/Components/NeonNav.vue')['default']
    NeonOverlay: typeof import('./resources/js/Components/NeonOverlay.vue')['default']
    NeonSocialActions: typeof import('./resources/js/Components/NeonSocialActions.vue')['default']
    NeonSocialCore: typeof import('./resources/js/Components/NeonSocialCore.vue')['default']
    NeonSocialFeed: typeof import('./resources/js/Components/NeonSocialFeed.vue')['default']
    NeonSocialPost: typeof import('./resources/js/Components/NeonSocialPost.vue')['default']
    NeonTechDashboard: typeof import('./resources/js/Components/NeonTechDashboard.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
  }
}
