<?php

namespace App\Ai\Agents\Actions\Ai;

use App\Actions\SendMessageAction;
use App\Ai\Agents\Actions\AIAction;
use App\Ai\Agents\AIAgent;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;

class ExecuteSendMessageAction implements AIAction
{
    public function __construct(
        private readonly SendMessageAction $sendMessageAction,
        private AIAgent $agent
    ) {}

    public function execute(User $user, array $payload): void
    {
        $recipientId = $payload['recipient_id'] ?? null;

        if (! $recipientId) {
            Log::warning('send_message: missing recipient_id in payload.');

            return;
        }

        $recipient = User::find($recipientId);

        if (! $recipient || $recipient->is_ai) {
            Log::warning("send_message: recipient_id [{$recipientId}] is not a valid human user.");

            return;
        }

        $this->agent->withPersona($user->name);

        $conversation = DB::table('agent_conversations')
            ->where('agent_user_id', $user->id)
            ->where('user_id', $recipientId)
            ->first();

        $conversationId = $conversation?->id;
        $lastMessage = null;

        if ($conversationId) {
            $lastMessage = DB::table('agent_conversation_messages')
                ->where('conversation_id', $conversationId)
                ->orderBy('created_at', 'desc')
                ->first();

            $this->agent->loadConversation((string) $conversationId);
        }

        // Pokud poslední zprávu poslal bot a uživatel neodpověděl, akci přeskočíme
        if ($lastMessage && $lastMessage->role !== 'user') {
            Log::info("AI action skipped: Bot {$user->name} waiting for user response.");

            return;
        }

        $response = $this->agent->prompt(
            'Generate the next short message reply to the user. Keep it strictly under 2 short sentences. Do not wrap in quotes. Speak completely in English matching your exact persona.',
            provider: ['groq']
        );

        // Očistíme vygenerovaný text od uvozovek a okrajových mezer
        $botMessageText = Str::of($response->text ?? '')
            ->trim()
            ->replace(['"', "'"], '')
            ->toString();

        if (empty($botMessageText)) {
            Log::warning("AI action failed: empty message text generated by bot [{$user->name}]");

            return;
        }

        $this->sendMessageAction->execute(
            $user->id,
            $recipientId,
            $botMessageText,
            $user->name
        );

        Log::info("AI action broadcasted: send_message from bot [{$user->name}] to user {$recipientId}");
    }
}
